/**
 * Convert bundled single-melody MIDI files into static TypeScript data.
 * Run: npx tsx scripts/convert-midi.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const { Midi } = require('@tonejs/midi') as typeof import('@tonejs/midi')

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const midiDir = join(root, 'assets', 'midi')
const manifestPath = join(midiDir, 'manifest.json')
const outPath = join(root, 'src', 'data', 'melodies.generated.ts')

interface ManifestEntry {
  id: string
  file: string
  title: string
  source: string
  keySignature: number
  bpm?: number
  timeSignature?: [number, number]
}

export interface MelodyNoteData {
  midi: number
  startBeat: number
  durationBeats: number
  barIndex: number
}

export interface MelodyData {
  id: string
  title: string
  source: string
  bpm: number
  timeSignature: [number, number]
  keySignature: number
  barCount: number
  notes: MelodyNoteData[]
}

const START_EPS = 1e-6

function roundBeat(value: number): number {
  return Math.round(value * 1000) / 1000
}

function convertFile(entry: ManifestEntry): MelodyData {
  const filePath = join(midiDir, entry.file)
  const buffer = readFileSync(filePath)
  const midi = new Midi(buffer)

  const track = midi.tracks.find(t => t.notes.length > 0)
  if (!track) {
    throw new Error(`[${entry.id}] no notes found in ${entry.file}`)
  }

  const tsEvent = midi.header.timeSignatures[0]
  if (!tsEvent && !entry.timeSignature) {
    throw new Error(`[${entry.id}] missing time signature in MIDI and manifest`)
  }

  const timeSignature: [number, number] = entry.timeSignature
    ?? [tsEvent!.timeSignature[0] ?? 4, tsEvent!.timeSignature[1] ?? 4]

  const beatsPerBar = timeSignature[0]
  const ppq = midi.header.ppq
  if (!ppq) {
    throw new Error(`[${entry.id}] invalid PPQ`)
  }

  const bpm = entry.bpm
    ?? midi.header.tempos[0]?.bpm
    ?? 120

  const sorted = [...track.notes].sort((a, b) => a.ticks - b.ticks || a.midi - b.midi)
  const notes: MelodyNoteData[] = []

  for (const note of sorted) {
    const startBeat = roundBeat(note.ticks / ppq)
    const durationBeats = roundBeat(Math.max(note.durationTicks / ppq, 0.25))

    const clash = notes.find(n => Math.abs(n.startBeat - startBeat) < START_EPS)
    if (clash) {
      throw new Error(
        `[${entry.id}] polyphonic onset at beat ${startBeat}: midi ${clash.midi} and ${note.midi}`,
      )
    }

    const barIndex = Math.floor(startBeat / beatsPerBar + START_EPS)
    notes.push({ midi: note.midi, startBeat, durationBeats, barIndex })
  }

  if (notes.length === 0) {
    throw new Error(`[${entry.id}] converted zero notes`)
  }

  const last = notes[notes.length - 1]
  const endBeat = last.startBeat + last.durationBeats
  const barCount = Math.max(last.barIndex + 1, Math.ceil(endBeat / beatsPerBar - START_EPS))

  return {
    id: entry.id,
    title: entry.title,
    source: entry.source,
    bpm,
    timeSignature,
    keySignature: entry.keySignature,
    barCount,
    notes,
  }
}

function serialize(melodies: MelodyData[]): string {
  const body = JSON.stringify(melodies, null, 2)
  return `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/convert-midi.ts — do not edit by hand.
 * Source: assets/midi/
 */

export const GENERATED_MELODIES = ${body} as const
`
}

function main() {
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as ManifestEntry[]
  const midiFiles = new Set(
    readdirSync(midiDir).filter(name => /\.midi?$/i.test(name)),
  )

  const melodies: MelodyData[] = []
  for (const entry of manifest) {
    if (!midiFiles.has(entry.file)) {
      throw new Error(`[${entry.id}] missing file ${entry.file}`)
    }
    const melody = convertFile(entry)
    melodies.push(melody)
    console.log(
      `converted ${entry.id}: ${melody.notes.length} notes, ${melody.barCount} bars, ${melody.timeSignature[0]}/${melody.timeSignature[1]}`,
    )
  }

  writeFileSync(outPath, serialize(melodies), 'utf8')
  console.log(`wrote ${outPath}`)
}

main()
