/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/convert-midi.ts — do not edit by hand.
 * Source: assets/midi/
 */

export const GENERATED_MELODIES = [
  {
    "id": "twinkle",
    "title": "小星星",
    "source": "Traditional / public domain",
    "bpm": 100,
    "timeSignature": [
      4,
      4
    ],
    "keySignature": 0,
    "barCount": 12,
    "notes": [
      {
        "midi": 60,
        "startBeat": 0,
        "durationBeats": 1,
        "barIndex": 0
      },
      {
        "midi": 60,
        "startBeat": 1,
        "durationBeats": 1,
        "barIndex": 0
      },
      {
        "midi": 67,
        "startBeat": 2,
        "durationBeats": 1,
        "barIndex": 0
      },
      {
        "midi": 67,
        "startBeat": 3,
        "durationBeats": 1,
        "barIndex": 0
      },
      {
        "midi": 69,
        "startBeat": 4,
        "durationBeats": 1,
        "barIndex": 1
      },
      {
        "midi": 69,
        "startBeat": 5,
        "durationBeats": 1,
        "barIndex": 1
      },
      {
        "midi": 67,
        "startBeat": 6,
        "durationBeats": 2,
        "barIndex": 1
      },
      {
        "midi": 65,
        "startBeat": 8,
        "durationBeats": 1,
        "barIndex": 2
      },
      {
        "midi": 65,
        "startBeat": 9,
        "durationBeats": 1,
        "barIndex": 2
      },
      {
        "midi": 64,
        "startBeat": 10,
        "durationBeats": 1,
        "barIndex": 2
      },
      {
        "midi": 64,
        "startBeat": 11,
        "durationBeats": 1,
        "barIndex": 2
      },
      {
        "midi": 62,
        "startBeat": 12,
        "durationBeats": 1,
        "barIndex": 3
      },
      {
        "midi": 62,
        "startBeat": 13,
        "durationBeats": 1,
        "barIndex": 3
      },
      {
        "midi": 60,
        "startBeat": 14,
        "durationBeats": 2,
        "barIndex": 3
      },
      {
        "midi": 67,
        "startBeat": 16,
        "durationBeats": 1,
        "barIndex": 4
      },
      {
        "midi": 67,
        "startBeat": 17,
        "durationBeats": 1,
        "barIndex": 4
      },
      {
        "midi": 65,
        "startBeat": 18,
        "durationBeats": 1,
        "barIndex": 4
      },
      {
        "midi": 65,
        "startBeat": 19,
        "durationBeats": 1,
        "barIndex": 4
      },
      {
        "midi": 64,
        "startBeat": 20,
        "durationBeats": 1,
        "barIndex": 5
      },
      {
        "midi": 64,
        "startBeat": 21,
        "durationBeats": 1,
        "barIndex": 5
      },
      {
        "midi": 62,
        "startBeat": 22,
        "durationBeats": 2,
        "barIndex": 5
      },
      {
        "midi": 67,
        "startBeat": 24,
        "durationBeats": 1,
        "barIndex": 6
      },
      {
        "midi": 67,
        "startBeat": 25,
        "durationBeats": 1,
        "barIndex": 6
      },
      {
        "midi": 65,
        "startBeat": 26,
        "durationBeats": 1,
        "barIndex": 6
      },
      {
        "midi": 65,
        "startBeat": 27,
        "durationBeats": 1,
        "barIndex": 6
      },
      {
        "midi": 64,
        "startBeat": 28,
        "durationBeats": 1,
        "barIndex": 7
      },
      {
        "midi": 64,
        "startBeat": 29,
        "durationBeats": 1,
        "barIndex": 7
      },
      {
        "midi": 62,
        "startBeat": 30,
        "durationBeats": 2,
        "barIndex": 7
      },
      {
        "midi": 60,
        "startBeat": 32,
        "durationBeats": 1,
        "barIndex": 8
      },
      {
        "midi": 60,
        "startBeat": 33,
        "durationBeats": 1,
        "barIndex": 8
      },
      {
        "midi": 67,
        "startBeat": 34,
        "durationBeats": 1,
        "barIndex": 8
      },
      {
        "midi": 67,
        "startBeat": 35,
        "durationBeats": 1,
        "barIndex": 8
      },
      {
        "midi": 69,
        "startBeat": 36,
        "durationBeats": 1,
        "barIndex": 9
      },
      {
        "midi": 69,
        "startBeat": 37,
        "durationBeats": 1,
        "barIndex": 9
      },
      {
        "midi": 67,
        "startBeat": 38,
        "durationBeats": 2,
        "barIndex": 9
      },
      {
        "midi": 65,
        "startBeat": 40,
        "durationBeats": 1,
        "barIndex": 10
      },
      {
        "midi": 65,
        "startBeat": 41,
        "durationBeats": 1,
        "barIndex": 10
      },
      {
        "midi": 64,
        "startBeat": 42,
        "durationBeats": 1,
        "barIndex": 10
      },
      {
        "midi": 64,
        "startBeat": 43,
        "durationBeats": 1,
        "barIndex": 10
      },
      {
        "midi": 62,
        "startBeat": 44,
        "durationBeats": 1,
        "barIndex": 11
      },
      {
        "midi": 62,
        "startBeat": 45,
        "durationBeats": 1,
        "barIndex": 11
      },
      {
        "midi": 60,
        "startBeat": 46,
        "durationBeats": 2,
        "barIndex": 11
      }
    ]
  },
  {
    "id": "canon",
    "title": "卡农",
    "source": "Traditional / public domain",
    "bpm": 90,
    "timeSignature": [
      4,
      4
    ],
    "keySignature": 0,
    "barCount": 49,
    "notes": [
      {
        "midi": 76,
        "startBeat": 0,
        "durationBeats": 3.6,
        "barIndex": 0
      },
      {
        "midi": 74,
        "startBeat": 4,
        "durationBeats": 3.6,
        "barIndex": 1
      },
      {
        "midi": 72,
        "startBeat": 8,
        "durationBeats": 3.6,
        "barIndex": 2
      },
      {
        "midi": 71,
        "startBeat": 12,
        "durationBeats": 3.6,
        "barIndex": 3
      },
      {
        "midi": 69,
        "startBeat": 16,
        "durationBeats": 3.6,
        "barIndex": 4
      },
      {
        "midi": 67,
        "startBeat": 20,
        "durationBeats": 3.6,
        "barIndex": 5
      },
      {
        "midi": 69,
        "startBeat": 24,
        "durationBeats": 3.6,
        "barIndex": 6
      },
      {
        "midi": 71,
        "startBeat": 28,
        "durationBeats": 3.6,
        "barIndex": 7
      },
      {
        "midi": 76,
        "startBeat": 32,
        "durationBeats": 1.8,
        "barIndex": 8
      },
      {
        "midi": 76,
        "startBeat": 34,
        "durationBeats": 0.9,
        "barIndex": 8
      },
      {
        "midi": 72,
        "startBeat": 35,
        "durationBeats": 0.9,
        "barIndex": 8
      },
      {
        "midi": 74,
        "startBeat": 36,
        "durationBeats": 2.7,
        "barIndex": 9
      },
      {
        "midi": 71,
        "startBeat": 39,
        "durationBeats": 0.9,
        "barIndex": 9
      },
      {
        "midi": 72,
        "startBeat": 40,
        "durationBeats": 1.8,
        "barIndex": 10
      },
      {
        "midi": 72,
        "startBeat": 42,
        "durationBeats": 0.9,
        "barIndex": 10
      },
      {
        "midi": 69,
        "startBeat": 43,
        "durationBeats": 0.9,
        "barIndex": 10
      },
      {
        "midi": 71,
        "startBeat": 44,
        "durationBeats": 2.7,
        "barIndex": 11
      },
      {
        "midi": 67,
        "startBeat": 47,
        "durationBeats": 0.9,
        "barIndex": 11
      },
      {
        "midi": 69,
        "startBeat": 48,
        "durationBeats": 1.8,
        "barIndex": 12
      },
      {
        "midi": 69,
        "startBeat": 50,
        "durationBeats": 0.9,
        "barIndex": 12
      },
      {
        "midi": 65,
        "startBeat": 51,
        "durationBeats": 0.9,
        "barIndex": 12
      },
      {
        "midi": 67,
        "startBeat": 52,
        "durationBeats": 2.7,
        "barIndex": 13
      },
      {
        "midi": 64,
        "startBeat": 55,
        "durationBeats": 0.9,
        "barIndex": 13
      },
      {
        "midi": 69,
        "startBeat": 56,
        "durationBeats": 1.8,
        "barIndex": 14
      },
      {
        "midi": 69,
        "startBeat": 58,
        "durationBeats": 0.9,
        "barIndex": 14
      },
      {
        "midi": 72,
        "startBeat": 59,
        "durationBeats": 0.9,
        "barIndex": 14
      },
      {
        "midi": 71,
        "startBeat": 60,
        "durationBeats": 1.8,
        "barIndex": 15
      },
      {
        "midi": 72,
        "startBeat": 62,
        "durationBeats": 0.9,
        "barIndex": 15
      },
      {
        "midi": 74,
        "startBeat": 63,
        "durationBeats": 0.9,
        "barIndex": 15
      },
      {
        "midi": 76,
        "startBeat": 64,
        "durationBeats": 0.9,
        "barIndex": 16
      },
      {
        "midi": 74,
        "startBeat": 65,
        "durationBeats": 0.9,
        "barIndex": 16
      },
      {
        "midi": 76,
        "startBeat": 66,
        "durationBeats": 0.9,
        "barIndex": 16
      },
      {
        "midi": 77,
        "startBeat": 67,
        "durationBeats": 0.9,
        "barIndex": 16
      },
      {
        "midi": 79,
        "startBeat": 68,
        "durationBeats": 0.9,
        "barIndex": 17
      },
      {
        "midi": 74,
        "startBeat": 69,
        "durationBeats": 0.9,
        "barIndex": 17
      },
      {
        "midi": 79,
        "startBeat": 70,
        "durationBeats": 0.9,
        "barIndex": 17
      },
      {
        "midi": 77,
        "startBeat": 71,
        "durationBeats": 0.9,
        "barIndex": 17
      },
      {
        "midi": 76,
        "startBeat": 72,
        "durationBeats": 0.9,
        "barIndex": 18
      },
      {
        "midi": 81,
        "startBeat": 73,
        "durationBeats": 0.9,
        "barIndex": 18
      },
      {
        "midi": 79,
        "startBeat": 74,
        "durationBeats": 0.9,
        "barIndex": 18
      },
      {
        "midi": 77,
        "startBeat": 75,
        "durationBeats": 0.9,
        "barIndex": 18
      },
      {
        "midi": 79,
        "startBeat": 76,
        "durationBeats": 0.9,
        "barIndex": 19
      },
      {
        "midi": 77,
        "startBeat": 77,
        "durationBeats": 0.9,
        "barIndex": 19
      },
      {
        "midi": 76,
        "startBeat": 78,
        "durationBeats": 0.9,
        "barIndex": 19
      },
      {
        "midi": 74,
        "startBeat": 79,
        "durationBeats": 0.9,
        "barIndex": 19
      },
      {
        "midi": 72,
        "startBeat": 80,
        "durationBeats": 0.9,
        "barIndex": 20
      },
      {
        "midi": 69,
        "startBeat": 81,
        "durationBeats": 0.9,
        "barIndex": 20
      },
      {
        "midi": 81,
        "startBeat": 82,
        "durationBeats": 0.9,
        "barIndex": 20
      },
      {
        "midi": 83,
        "startBeat": 83,
        "durationBeats": 0.9,
        "barIndex": 20
      },
      {
        "midi": 84,
        "startBeat": 84,
        "durationBeats": 0.9,
        "barIndex": 21
      },
      {
        "midi": 83,
        "startBeat": 85,
        "durationBeats": 0.9,
        "barIndex": 21
      },
      {
        "midi": 81,
        "startBeat": 86,
        "durationBeats": 0.9,
        "barIndex": 21
      },
      {
        "midi": 79,
        "startBeat": 87,
        "durationBeats": 0.9,
        "barIndex": 21
      },
      {
        "midi": 77,
        "startBeat": 88,
        "durationBeats": 0.9,
        "barIndex": 22
      },
      {
        "midi": 76,
        "startBeat": 89,
        "durationBeats": 0.9,
        "barIndex": 22
      },
      {
        "midi": 74,
        "startBeat": 90,
        "durationBeats": 0.9,
        "barIndex": 22
      },
      {
        "midi": 81,
        "startBeat": 91,
        "durationBeats": 0.9,
        "barIndex": 22
      },
      {
        "midi": 79,
        "startBeat": 92,
        "durationBeats": 0.9,
        "barIndex": 23
      },
      {
        "midi": 81,
        "startBeat": 93,
        "durationBeats": 0.9,
        "barIndex": 23
      },
      {
        "midi": 79,
        "startBeat": 94,
        "durationBeats": 0.9,
        "barIndex": 23
      },
      {
        "midi": 77,
        "startBeat": 95,
        "durationBeats": 0.9,
        "barIndex": 23
      },
      {
        "midi": 79,
        "startBeat": 96,
        "durationBeats": 0.9,
        "barIndex": 24
      },
      {
        "midi": 76,
        "startBeat": 97,
        "durationBeats": 0.45,
        "barIndex": 24
      },
      {
        "midi": 77,
        "startBeat": 97.5,
        "durationBeats": 0.45,
        "barIndex": 24
      },
      {
        "midi": 79,
        "startBeat": 98,
        "durationBeats": 0.9,
        "barIndex": 24
      },
      {
        "midi": 76,
        "startBeat": 99,
        "durationBeats": 0.45,
        "barIndex": 24
      },
      {
        "midi": 77,
        "startBeat": 99.5,
        "durationBeats": 0.45,
        "barIndex": 24
      },
      {
        "midi": 79,
        "startBeat": 100,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 67,
        "startBeat": 100.5,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 69,
        "startBeat": 101,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 71,
        "startBeat": 101.5,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 72,
        "startBeat": 102,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 74,
        "startBeat": 102.5,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 76,
        "startBeat": 103,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 77,
        "startBeat": 103.5,
        "durationBeats": 0.45,
        "barIndex": 25
      },
      {
        "midi": 76,
        "startBeat": 104,
        "durationBeats": 0.9,
        "barIndex": 26
      },
      {
        "midi": 72,
        "startBeat": 105,
        "durationBeats": 0.45,
        "barIndex": 26
      },
      {
        "midi": 74,
        "startBeat": 105.5,
        "durationBeats": 0.45,
        "barIndex": 26
      },
      {
        "midi": 76,
        "startBeat": 106,
        "durationBeats": 0.9,
        "barIndex": 26
      },
      {
        "midi": 64,
        "startBeat": 107,
        "durationBeats": 0.45,
        "barIndex": 26
      },
      {
        "midi": 65,
        "startBeat": 107.5,
        "durationBeats": 0.45,
        "barIndex": 26
      },
      {
        "midi": 67,
        "startBeat": 108,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 69,
        "startBeat": 108.5,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 67,
        "startBeat": 109,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 65,
        "startBeat": 109.5,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 67,
        "startBeat": 110,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 64,
        "startBeat": 110.5,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 65,
        "startBeat": 111,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 67,
        "startBeat": 111.5,
        "durationBeats": 0.45,
        "barIndex": 27
      },
      {
        "midi": 65,
        "startBeat": 112,
        "durationBeats": 0.9,
        "barIndex": 28
      },
      {
        "midi": 69,
        "startBeat": 113,
        "durationBeats": 0.45,
        "barIndex": 28
      },
      {
        "midi": 67,
        "startBeat": 113.5,
        "durationBeats": 0.45,
        "barIndex": 28
      },
      {
        "midi": 65,
        "startBeat": 114,
        "durationBeats": 0.9,
        "barIndex": 28
      },
      {
        "midi": 64,
        "startBeat": 115,
        "durationBeats": 0.45,
        "barIndex": 28
      },
      {
        "midi": 62,
        "startBeat": 115.5,
        "durationBeats": 0.45,
        "barIndex": 28
      },
      {
        "midi": 64,
        "startBeat": 116,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 62,
        "startBeat": 116.5,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 60,
        "startBeat": 117,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 62,
        "startBeat": 117.5,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 64,
        "startBeat": 118,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 65,
        "startBeat": 118.5,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 67,
        "startBeat": 119,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 69,
        "startBeat": 119.5,
        "durationBeats": 0.45,
        "barIndex": 29
      },
      {
        "midi": 65,
        "startBeat": 120,
        "durationBeats": 0.9,
        "barIndex": 30
      },
      {
        "midi": 69,
        "startBeat": 121,
        "durationBeats": 0.45,
        "barIndex": 30
      },
      {
        "midi": 67,
        "startBeat": 121.5,
        "durationBeats": 0.45,
        "barIndex": 30
      },
      {
        "midi": 69,
        "startBeat": 122,
        "durationBeats": 0.9,
        "barIndex": 30
      },
      {
        "midi": 71,
        "startBeat": 123,
        "durationBeats": 0.45,
        "barIndex": 30
      },
      {
        "midi": 72,
        "startBeat": 123.5,
        "durationBeats": 0.45,
        "barIndex": 30
      },
      {
        "midi": 67,
        "startBeat": 124,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 69,
        "startBeat": 124.5,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 71,
        "startBeat": 125,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 72,
        "startBeat": 125.5,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 74,
        "startBeat": 126,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 76,
        "startBeat": 126.5,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 77,
        "startBeat": 127,
        "durationBeats": 0.45,
        "barIndex": 31
      },
      {
        "midi": 79,
        "startBeat": 127.5,
        "durationBeats": 0.417,
        "barIndex": 31
      },
      {
        "midi": 79,
        "startBeat": 128,
        "durationBeats": 2.7,
        "barIndex": 32
      },
      {
        "midi": 79,
        "startBeat": 131,
        "durationBeats": 0.917,
        "barIndex": 32
      },
      {
        "midi": 79,
        "startBeat": 132,
        "durationBeats": 0.9,
        "barIndex": 33
      },
      {
        "midi": 81,
        "startBeat": 133,
        "durationBeats": 0.9,
        "barIndex": 33
      },
      {
        "midi": 79,
        "startBeat": 134,
        "durationBeats": 0.9,
        "barIndex": 33
      },
      {
        "midi": 77,
        "startBeat": 135,
        "durationBeats": 0.9,
        "barIndex": 33
      },
      {
        "midi": 76,
        "startBeat": 136,
        "durationBeats": 2.7,
        "barIndex": 34
      },
      {
        "midi": 76,
        "startBeat": 139,
        "durationBeats": 0.917,
        "barIndex": 34
      },
      {
        "midi": 76,
        "startBeat": 140,
        "durationBeats": 0.9,
        "barIndex": 35
      },
      {
        "midi": 77,
        "startBeat": 141,
        "durationBeats": 0.9,
        "barIndex": 35
      },
      {
        "midi": 76,
        "startBeat": 142,
        "durationBeats": 0.9,
        "barIndex": 35
      },
      {
        "midi": 74,
        "startBeat": 143,
        "durationBeats": 0.9,
        "barIndex": 35
      },
      {
        "midi": 72,
        "startBeat": 144,
        "durationBeats": 2.7,
        "barIndex": 36
      },
      {
        "midi": 72,
        "startBeat": 147,
        "durationBeats": 0.917,
        "barIndex": 36
      },
      {
        "midi": 72,
        "startBeat": 148,
        "durationBeats": 0.9,
        "barIndex": 37
      },
      {
        "midi": 74,
        "startBeat": 149,
        "durationBeats": 0.9,
        "barIndex": 37
      },
      {
        "midi": 72,
        "startBeat": 150,
        "durationBeats": 0.9,
        "barIndex": 37
      },
      {
        "midi": 70,
        "startBeat": 151,
        "durationBeats": 0.9,
        "barIndex": 37
      },
      {
        "midi": 69,
        "startBeat": 152,
        "durationBeats": 2.7,
        "barIndex": 38
      },
      {
        "midi": 72,
        "startBeat": 155,
        "durationBeats": 0.9,
        "barIndex": 38
      },
      {
        "midi": 71,
        "startBeat": 156,
        "durationBeats": 1.8,
        "barIndex": 39
      },
      {
        "midi": 72,
        "startBeat": 158,
        "durationBeats": 0.9,
        "barIndex": 39
      },
      {
        "midi": 74,
        "startBeat": 159,
        "durationBeats": 0.9,
        "barIndex": 39
      },
      {
        "midi": 76,
        "startBeat": 160,
        "durationBeats": 3.6,
        "barIndex": 40
      },
      {
        "midi": 74,
        "startBeat": 164,
        "durationBeats": 3.6,
        "barIndex": 41
      },
      {
        "midi": 72,
        "startBeat": 168,
        "durationBeats": 3.6,
        "barIndex": 42
      },
      {
        "midi": 71,
        "startBeat": 172,
        "durationBeats": 3.6,
        "barIndex": 43
      },
      {
        "midi": 69,
        "startBeat": 176,
        "durationBeats": 3.6,
        "barIndex": 44
      },
      {
        "midi": 67,
        "startBeat": 180,
        "durationBeats": 3.6,
        "barIndex": 45
      },
      {
        "midi": 69,
        "startBeat": 184,
        "durationBeats": 2.7,
        "barIndex": 46
      },
      {
        "midi": 72,
        "startBeat": 187,
        "durationBeats": 0.9,
        "barIndex": 46
      },
      {
        "midi": 71,
        "startBeat": 188,
        "durationBeats": 0.45,
        "barIndex": 47
      },
      {
        "midi": 72,
        "startBeat": 188.5,
        "durationBeats": 0.45,
        "barIndex": 47
      },
      {
        "midi": 71,
        "startBeat": 189,
        "durationBeats": 0.45,
        "barIndex": 47
      },
      {
        "midi": 72,
        "startBeat": 189.5,
        "durationBeats": 0.45,
        "barIndex": 47
      },
      {
        "midi": 71,
        "startBeat": 190,
        "durationBeats": 0.3,
        "barIndex": 47
      },
      {
        "midi": 72,
        "startBeat": 190.333,
        "durationBeats": 0.3,
        "barIndex": 47
      },
      {
        "midi": 71,
        "startBeat": 190.667,
        "durationBeats": 0.3,
        "barIndex": 47
      },
      {
        "midi": 69,
        "startBeat": 191,
        "durationBeats": 0.45,
        "barIndex": 47
      },
      {
        "midi": 71,
        "startBeat": 191.5,
        "durationBeats": 0.45,
        "barIndex": 47
      },
      {
        "midi": 72,
        "startBeat": 192,
        "durationBeats": 3.6,
        "barIndex": 48
      }
    ]
  }
] as const
